######################################################################
# Automatically generated by qmake (2.01a) lun. janv. 16 17:19:58 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += libparamtuner.h ParamTuner.hpp
SOURCES += consoleExample.cpp libparamtuner.cpp ParamTuner.cpp
